### ISSUE TITLE
Specify open source license

### ISSUE THREAD

**Issue by lindenthal** [VonRehbergConsulting/open-time-tracker#22]
Hi @VonRehberg, 
I was just wondering what the license of this app is. Did you specify this somewhere?
Best
Niels

**Comment by VonRehberg** [comment]
Hi Niels,
Just added the MIT license. :-)
BR,
Joschi

**Comment by lindenthal** [comment]
Hi Joschi,
Thanks for your quick response. Please let us know if you need anything.
Best
Niels

**Comment by VonRehberg** [comment]
Sure thing!

There is one thing, that you guys could potentially help us with. I don't really like the setup experience of the app at the moment. It works but it's cumbersome.
If we are super bored in the future, I would love to implement a backend package that offers two things:
* If you are an admin you can enable the time tracking app (which basically sets up the OAuth client with the correct parameters)
* If you are a normal user, you will be presented a QR code, which contains the instance URL and client id. This QR code can then be scanned in the app in order to improve the setup experience

In case somebody from Open Projects has time it would be awesome to get a rough estimation on how complicated the implementation would be. And maybe a very short introduction on where we would have to start if we would implement that package, because we have no idea how ruby projects work.
