### ISSUE TITLE
Basic APP issue

### ISSUE THREAD

**Issue by ckvtz** [VonRehbergConsulting/open-time-tracker#26]
Hi there,

Great APP and very useful one indeed.

New tasks added to a project in the web APP not getting displayed in the -Active Tasks- page of your APP even after swipe down to refresh.

It would be great if we can add a task to projects as it would help us avoid being in front of a computer.

Thank you.

**Comment by oleksiiborysenko** [comment]
Hi guys.  
I also noticed that there is an issue with ActiveTasks tabs. it looks like that is related to filters. 
@VonRehberg, will it be ok if I add a PR with workaround for this issue?

**Comment by VonRehberg** [comment]
We're always happy for contributions, so feel free to create a merge request.
Although I think I still don't fully get the issue.

You create a new task in Open Project web UI and assign it to your user and it's still not visible?
I guess since everyone uses Open Project slightly different maybe it makes sense to allow to toggle between "My tasks" and all project tasks.

**Comment by oleksiiborysenko** [comment]
> You create a new task in Open Project web UI and assign it to your user and it's still not visible?
yeah, it's empty now

> it makes sense to allow to toggle between "My tasks" and all project tasks.
From what I can see at first glance - filtering by user isn't working as expected, so adding a toggle indeed can help as well.

> so feel free to create a merge request.
Thanks, will do.

**Comment by VonRehberg** [comment]
I just checked the code and see the following reasons for the work packages not being displayed:
1. it currently filters on tasks only (should be extended to all work package types except from milestones)
2. filters out closed and rejected work packages.

@denisshtangey can you please take a look?

**Comment by lindenthal** [comment]
Hi @VonRehberg,
Thanks a lot for this exchange here. 

Please allow me to give you more background information.
Here at OpenProject we don't have very much expertise and capacity for app development. And since it is an important thing for the community I asked @oleksiiborysenko (external app developer) to reach out to you and to offer his support. My goal is to contribute to your app but also to get a better understanding how app development with Flutter is different from OpenProject developement with RoR in terms of development velocity, release process and so on.

If you want I can ask @parimalsatyal from our UX team to support with mockups.

Getting back to the toggle idea.

> I guess since everyone uses Open Project slightly different maybe it makes sense to allow to toggle between "My tasks" and all project tasks.

Would it be an option as a first step to use an existing query that is defined in the web? So a list like this one here:

https://community.openproject.org/projects/14/work_packages?query_id=918

Best
Niels

**Comment by VonRehberg** [comment]
Hi Niels,

Some support would be awesome :-)
Fetching work packages from queries wouldn't be a big deal I guess. It's rather a UX question and in which direction the time tracker should develop.
We can also have a short call if you like, maybe it's faster to sort things out this way instead of endless threads here... I will reach out to you.

BR,
Joschi

**Comment by VonRehberg** [comment]
Denis provided PR #41 as a quick fix for the filter issue until we come up with a more sophisticated solution.
If there are no major objections, we could deploy this within the next 24h.

Although I think it might be weird that people record time on milestones, but maybe it's just me... 🤷🏻‍♂️

**Comment by VonRehberg** [comment]
@denisshtangey reworked the status filter and it's now possible to specify the work package statuses to be displayed.
I will close this issue for now.
If anyone wants to join testing in TestFlight, drop me a mail: cjeschke@vonrehberg.consulting
